name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
        tag_id: ${(steps.date.outputs.date)}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Get timesTamp
        id: date
        run: echo "date = \$(TZ='America/Bogota' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT  
      - name: Build the docker file
        run: docker build . --file Dockerfile --tag montoyita41/utbapp:&{{ steps.date.outputs.date }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        run: docker push montoyita41/utbapp:&{{ steps.date.outputs.date }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize Terraform
        run: |
          set -e
          cd ./terraform
          terraform init -input=false -chdir=./terraform/
          terraform init -input=false
          terraform plan -out plan.out
          terraform apply plan.out -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
                
        
