name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: DockerFileFolder/
          push: true
          tags: montoyita41/utbapp:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize Terraform
        run: |
          set -e
          cd ..terraform/main.tf
          terraform init -input=false -chdir=..terraform/main.tf
          terraform init -input=false
          terraform plan -out plan.out
          terraform apply plan.out -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
                
        
